project:
  type: website

website:
  title: "is415-gaa-grp12"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: "proposal.html"
        text: Proposal

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

